
spring:
  main:
    allow-circular-references: true
  datasource:
    password: myjournalpass
    username: journal
    url: jdbc:mysql://localhost:3306/journal?useUnicode=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
#        format_sql: true
#    show-sql: true
server:
  port: 8848
